apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        # Notez ici la version - c'est ce que vous changerez pour passer de v1 à v2
        image: wil42/playground:v1
        ports:
        - containerPort: 8888